import dynamic from "next/dynamic";
import { type Processes } from "contexts/process/types";
import {
  FOLDER_ICON,
  ICON_PATH,
  PROGRAM_FILES_PATH,
  TASKBAR_HEIGHT,
} from "utils/constants";

const directory: Processes = {
  BoxedWine: {
    Component: dynamic(() => import("components/apps/BoxedWine")),
    allowResizing: false,
    backgroundColor: "#000",
    defaultSize: {
      height: 480,
      width: 640,
    },
    dependantLibs: [`${PROGRAM_FILES_PATH}/BoxedWine/boxedwine.wasm`],
    icon: `${ICON_PATH}/boxedwine.webp`,
    libs: [
      `${PROGRAM_FILES_PATH}/BoxedWine/browserfs.boxedwine.js`,
      `${PROGRAM_FILES_PATH}/BoxedWine/boxedwine-shell.js`,
      `${PROGRAM_FILES_PATH}/BoxedWine/boxedwine.js`,
    ],
    lockAspectRatio: true,
    singleton: true,
    title: "BoxedWine",
  },
  Browser: {
    Component: dynamic(() => import("components/apps/Browser")),
    backgroundColor: "#FFF",
    defaultSize: {
      height: 500,
      width: 600,
    },
    icon: `${ICON_PATH}/chromium.webp`,
    title: "Browser",
  },
  ClassiCube: {
    Component: dynamic(() => import("components/apps/ClassiCube")),
    backgroundColor: "#201E20",
    defaultSize: {
      height: 420,
      width: 640,
    },
    icon: `${ICON_PATH}/classicube.webp`,
    libs: [`${PROGRAM_FILES_PATH}/ClassiCube/ClassiCube.js`],
    title: "ClassiCube",
  },
  DXBall: {
    Component: dynamic(() => import("components/apps/DX-Ball")),
    backgroundColor: "#000",
    icon: `${ICON_PATH}/dxball.webp`,
    libs: [`${PROGRAM_FILES_PATH}/DX-Ball/game.js`],
    lockAspectRatio: true,
    singleton: true,
    title: "DX-Ball",
  },
  DevTools: {
    Component: dynamic(() => import("components/apps/DevTools")),
    backgroundColor: "#242424",
    defaultSize: {
      height: 380,
      width: 545,
    },
    icon: `${ICON_PATH}/eruda.webp`,
    libs: [
      `${PROGRAM_FILES_PATH}/Eruda/eruda.js`,
      `${PROGRAM_FILES_PATH}/Eruda/eruda-monitor.js`,
    ],
    singleton: true,
    title: "DevTools",
  },
  Emulator: {
    Component: dynamic(() => import("components/apps/Emulator")),
    backgroundColor: "#000",
    defaultSize: {
      height: 400,
      width: 600,
    },
    dependantLibs: [
      `${PROGRAM_FILES_PATH}/EmulatorJs/emu-css.min.css`,
      `${PROGRAM_FILES_PATH}/EmulatorJs/emulator.min.js`,
    ],
    icon: `${ICON_PATH}/emulator.webp`,
    libs: [`${PROGRAM_FILES_PATH}/EmulatorJs/loader.js`],
    lockAspectRatio: true,
    title: "Emulator",
  },
  FileExplorer: {
    Component: dynamic(() => import("components/apps/FileExplorer")),
    backgroundColor: "#202020",
    defaultSize: {
      height: 325,
      width: 447,
    },
    icon: FOLDER_ICON,
    title: "File Explorer",
  },
  IRC: {
    Component: dynamic(() => import("components/apps/IRC")),
    backgroundColor: "#FFF",
    defaultSize: {
      height: 512,
      width: 704,
    },
    icon: `${ICON_PATH}/kiwiirc.webp`,
    libs: [`${PROGRAM_FILES_PATH}/kiwiirc/index.html`],
    title: "IRC",
  },
  JSDOS: {
    Component: dynamic(() => import("components/apps/JSDOS")),
    autoSizing: true,
    backgroundColor: "#000",
    defaultSize: {
      height: 200,
      width: 320,
    },
    dependantLibs: [`${PROGRAM_FILES_PATH}/js-dos/wdosbox.wasm`],
    icon: `${ICON_PATH}/jsdos.webp`,
    libs: [
      `${PROGRAM_FILES_PATH}/js-dos/emulators.js`,
      `${PROGRAM_FILES_PATH}/js-dos/emulators-ui.js`,
    ],
    lockAspectRatio: true,
    title: "js-dos v7",
  },
  Marked: {
    Component: dynamic(() => import("components/apps/Marked")),
    backgroundColor: "#FFF",
    defaultSize: {
      height: 480,
      width: 560,
    },
    icon: `${ICON_PATH}/marked.webp`,
    libs: [
      `${PROGRAM_FILES_PATH}/Marked/marked.min.js`,
      `${PROGRAM_FILES_PATH}/Marked/purify.min.js`,
    ],
    title: "Marked",
  },
  Messenger: {
    Component: dynamic(() => import("components/apps/Messenger")),
    backgroundColor: "#242526",
    defaultSize: {
      height: 500,
      width: 425,
    },
    icon: `${ICON_PATH}/messenger.webp`,
    singleton: true,
    title: "Messenger",
  },
  MonacoEditor: {
    Component: dynamic(() => import("components/apps/MonacoEditor")),
    backgroundColor: "#1E1E1E",
    defaultSize: {
      height: 480,
      width: 544,
    },
    dependantLibs: [
      `${PROGRAM_FILES_PATH}/MonacoEditor/vs/loader.js`,
      `${PROGRAM_FILES_PATH}/MonacoEditor/vs/editor/editor.main.js`,
      `${PROGRAM_FILES_PATH}/MonacoEditor/vs/editor/editor.main.css`,
      `${PROGRAM_FILES_PATH}/MonacoEditor/vs/editor/editor.main.nls.js`,
    ],
    icon: `${ICON_PATH}/monaco.webp`,
    title: "Monaco Editor",
  },
  OpenType: {
    Component: dynamic(() => import("components/apps/OpenType")),
    backgroundColor: "#FFF",
    icon: `${ICON_PATH}/opentype.webp`,
    preferProcessIcon: true,
    title: "OpenType",
  },
  OpenWith: {
    Component: dynamic(() => import("components/system/Dialogs/OpenWith")),
    allowResizing: false,
    backgroundColor: "#FFF",
    defaultSize: {
      height: 492,
      width: 392,
    },
    dialogProcess: true,
    hideTaskbarEntry: true,
    hideTitlebar: true,
    icon: `${ICON_PATH}/unknown.webp`,
    title: "Open With",
  },
  PDF: {
    Component: dynamic(() => import("components/apps/PDF")),
    backgroundColor: "#525659",
    icon: `${ICON_PATH}/pdf.webp`,
    libs: [`${PROGRAM_FILES_PATH}/PDF.js/pdf.js`],
    title: "PDF",
  },
  Paint: {
    Component: dynamic(() => import("components/apps/Paint")),
    backgroundColor: "#808080",
    icon: `${ICON_PATH}/paint.webp`,
    libs: [`${PROGRAM_FILES_PATH}/jspaint/index.html`],
    title: "Paint",
  },
  Photos: {
    Component: dynamic(() => import("components/apps/Photos")),
    backgroundColor: "#222",
    defaultSize: {
      height: 432,
      width: 576,
    },
    hideTitlebarIcon: true,
    icon: `${ICON_PATH}/photos.webp`,
    title: "Photos",
  },
  Properties: {
    Component: dynamic(() => import("components/system/Dialogs/Properties")),
    allowResizing: false,
    backgroundColor: "rgb(240, 240, 240)",
    defaultSize: {
      height: 412,
      width: 361,
    },
    dialogProcess: true,
    hideMaximizeButton: true,
    hideMinimizeButton: true,
    icon: "",
    title: "Properties",
  },
  Quake3: {
    Component: dynamic(() => import("components/apps/Quake3")),
    backgroundColor: "#000",
    defaultSize: {
      height: 480,
      width: 640,
    },
    icon: `${ICON_PATH}/quake3.webp`,
    libs: [`${PROGRAM_FILES_PATH}/Quake3/Quake3Game.js`],
    lockAspectRatio: true,
    title: "Quake III Arena",
  },
  Ruffle: {
    Component: dynamic(() => import("components/apps/Ruffle")),
    backgroundColor: "#000",
    defaultSize: {
      height: 400,
      width: 550,
    },
    icon: `${ICON_PATH}/ruffle.webp`,
    libs: [`${PROGRAM_FILES_PATH}/Ruffle/ruffle.js`],
    lockAspectRatio: true,
    title: "Ruffle",
  },
  Run: {
    Component: dynamic(() => import("components/system/Dialogs/Run")),
    allowResizing: false,
    defaultSize: {
      height: 174,
      width: 397,
    },
    dialogProcess: true,
    hideMaximizeButton: true,
    hideMinimizeButton: true,
    icon: `${ICON_PATH}/run.webp`,
    initialRelativePosition: {
      bottom: TASKBAR_HEIGHT + 11,
      left: 15,
    },
    singleton: true,
    title: "Run",
  },
  ScreenSaver: {
    Component: dynamic(() => import("components/system/Dialogs/ScreenSaver")),
    allowResizing: false,
    dialogProcess: true,
    hasWindow: false,
    hideTaskbarEntry: true,
    icon: `${ICON_PATH}/screensaver.webp`,
    singleton: true,
    title: "Screen Saver",
  },
  SpaceCadet: {
    Component: dynamic(() => import("components/apps/SpaceCadet")),
    backgroundColor: "#000",
    defaultSize: {
      height: 428,
      width: 600,
    },
    dependantLibs: [`${PROGRAM_FILES_PATH}/SpaceCadet/SpaceCadetPinball.wasm`],
    icon: `${ICON_PATH}/pinball.webp`,
    libs: [`${PROGRAM_FILES_PATH}/SpaceCadet/SpaceCadetPinball.js`],
    lockAspectRatio: true,
    title: "Space Cadet",
  },
  StableDiffusion: {
    Component: dynamic(() => import("components/apps/StableDiffusion")),
    backgroundColor: "rgb(235, 251, 247)",
    defaultSize: {
      height: 644,
      width: 538,
    },
    icon: `${ICON_PATH}/stablediffusion.webp`,
    singleton: true,
    title: "Stable Diffusion",
  },
  Terminal: {
    Component: dynamic(() => import("components/apps/Terminal")),
    backgroundBlur: "8px",
    backgroundColor: "rgba(12, 12, 12, 0.5)",
    defaultSize: {
      height: 374,
      width: 615,
    },
    icon: `${ICON_PATH}/xterm.webp`,
    libs: [
      `${PROGRAM_FILES_PATH}/Xterm.js/xterm.css`,
      `${PROGRAM_FILES_PATH}/Xterm.js/xterm.js`,
      `${PROGRAM_FILES_PATH}/Xterm.js/xterm-addon-fit.js`,
      `${PROGRAM_FILES_PATH}/Xterm.js/local-echo.js`,
    ],
    preferProcessIcon: true,
    title: "Terminal",
  },
  Tic80: {
    Component: dynamic(() => import("components/apps/Tic80")),
    backgroundColor: "#1A1C2C",
    defaultSize: {
      height: 346,
      width: 615,
    },
    dependantLibs: [`${PROGRAM_FILES_PATH}/Tic80/tic80.wasm`],
    icon: `${ICON_PATH}/tic80.webp`,
    libs: [`${PROGRAM_FILES_PATH}/Tic80/tic80.js`],
    lockAspectRatio: true,
    title: "TIC-80 tiny computer",
  },
  TinyMCE: {
    Component: dynamic(() => import("components/apps/TinyMCE")),
    backgroundColor: "#202124",
    dependantLibs: [
      `${PROGRAM_FILES_PATH}/TinyMCE/themes/silver/theme.min.js`,
      `${PROGRAM_FILES_PATH}/TinyMCE/models/dom/model.min.js`,
      `${PROGRAM_FILES_PATH}/TinyMCE/icons/default/icons.min.js`,
      `${PROGRAM_FILES_PATH}/TinyMCE/skins/ui/oxide/skin.min.css`,
    ],
    icon: `${ICON_PATH}/tinymce.webp`,
    libs: [`${PROGRAM_FILES_PATH}/TinyMCE/tinymce.min.js`],
    title: "TinyMCE",
  },
  Transfer: {
    Component: dynamic(() => import("components/system/Dialogs/Transfer")),
    allowResizing: false,
    backgroundColor: "#FFF",
    defaultSize: {
      height: 163,
      width: 400,
    },
    dialogProcess: true,
    icon: `${ICON_PATH}/copying.webp`,
    title: "",
  },
  V86: {
    Component: dynamic(() => import("components/apps/V86")),
    allowResizing: false,
    autoSizing: true,
    backgroundColor: "#000",
    defaultSize: {
      height: 200,
      width: 320,
    },
    dependantLibs: [`${PROGRAM_FILES_PATH}/Virtual x86/v86.wasm`],
    icon: `${ICON_PATH}/v86.webp`,
    libs: [`${PROGRAM_FILES_PATH}/Virtual x86/libv86.js`],
    preferProcessIcon: true,
    title: "Virtual x86",
  },
  VideoPlayer: {
    Component: dynamic(() => import("components/apps/VideoPlayer")),
    autoSizing: true,
    backgroundColor: "#000",
    defaultSize: {
      height: 390,
      width: 640,
    },
    icon: `${ICON_PATH}/vlc.webp`,
    libs: [
      `${PROGRAM_FILES_PATH}/Video.js/video-js.min.css`,
      `${PROGRAM_FILES_PATH}/Video.js/video.min.js`,
      `${PROGRAM_FILES_PATH}/Video.js/Youtube.min.js`,
    ],
    title: "Video Player",
  },
  Vim: {
    Component: dynamic(() => import("components/apps/Vim")),
    allowResizing: false,
    backgroundColor: "#222324",
    defaultSize: {
      height: 448,
      width: 595,
    },
    icon: `${ICON_PATH}/vim.webp`,
    libs: [`${PROGRAM_FILES_PATH}/Vim.js/vim.js`],
    singleton: true,
    title: "Vim",
  },
  Webamp: {
    Component: dynamic(() => import("components/apps/Webamp")),
    allowResizing: false,
    hasWindow: false,
    icon: `${ICON_PATH}/webamp.webp`,
    libs: [`${PROGRAM_FILES_PATH}/Webamp/webamp.bundle.min.js`],
    singleton: true,
    title: "Webamp",
  },
};

export default directory;
